#!/usr/bin/env bash
# requires: grim and slurp for wayland

cwd=$(pwd)
datetimeformatted="$(date +%F_%H-%M-%S)"
filename="screengrab_$datetimeformatted.png"
echo -n '[ScreenGrab] : 麗Select a region of the screen to grab...'
dimensions="$(slurp)"
grim -g "$dimensions" "$filename" && echo -ne "\r[ScreenGrab] :  written to $cwd/$filename\n" 

