#!/usr/bin/env bash
# SealyJ 2020
# requires: grim and slurp for wayland

cwd=$(pwd)
datetimeformatted="$(date +%F_%H-%M-%S)"
filename="screengrab_$datetimeformatted.png"
echo -n '[sssnatch] : 麗Select a region of the screen to grab...'
dimensions="$(slurp)"
if [ $? -ne 0 ] ; then
  exit 1
fi
grim -g "$dimensions" "$filename" && echo -ne "\r[sssnatch] :  written to $cwd/$filename\n" 

